version: '3'

services:

  mysql:
    image: mysql:8.0
    container_name: mysql-prove
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: prove_db
      MYSQL_USER: user
      MYSQL_PASSWORD: pass
    volumes:
      - ./data/mysql:/var/lib/mysql
      - ./environment/mysql-entrypoint:/docker-entrypoint-initdb.d
    ports:
      - 3306:3306

  webserver:
    container_name: webserver
    build:
      context: ./
    environment:
      XDEBUG_CONFIG: remote_host=host.docker.internal
      PHP_IDE_CONFIG: serverName=PHPServer
    volumes:
      - .:/var/www/html
    ports:
      - 80:80
